### ISSUE TITLE
Newbie-ish question

### ISSUE THREAD

**Issue by d0ugparker** [KokichaKolevTM/BG-Adblock-list#4]
Coming up to speed on different things. I hope you'll answer some newbie questions. 

I'm browsing some of my optional filters in the filter list in Brave browser on Windows 11 on my desktop. I'm going through a chain of discovery of the things I'm finding. Your adblock list looks like it may be related to one that's listed in Brave's suggested list of lists, but I'm not positive about that. So, question 1 would be, _“Is your BG-Adblock-list the same as the one Brave lists?”_

My second question has to do with the format of some of its lines. For example, 

`/^https?:\/\/cdn\.[a-z]{4,8}\.com\/app\.js$/$3p,script,match-case`

Is that all regular expression content? It _sort of_ looks like it is, but that ending part after the `“.js”` is throwing me. I may be making this harder than it really is. `“$”` is RE for _“end”_ and it just appends `“$3p.script.match-case”`. Is that right?

Lastly, I couldn't find a way to message others. I chose to contact you by using the ISSUES tab. If this form of connection is unconventional or unacceptable to github developers, please let me know what a better or more acceptable way of contacting and asking questions would be.

Thanks! Regards. Doug, Henderson, NV, USA

**Comment by KokichaKolevTM** [comment]
Hi! About the first question, my filterlist is not the same as the one in Brave's additional lists. It's the list maintained by https://stanev.org/ (https://stanev.org/abp/). His list is called "Bulgarian adblock list", mine is "Bulgarian Ads & Privacy". About the second question, yes, that's a regular expression (`/^https?:\/\/cdn\.[a-z]{4,8}\.com\/app\.js$/`), while everything after it are just filtering options (in this case it means block all third-party scripts that match the regex). If you are interested you can read about them in these webpages:
* https://adguard.com/kb/general/ad-filtering/create-own-filters/#basic-rules-modifiers
* https://help.adblockplus.org/hc/en-us/articles/360062733293-How-to-write-filters#options
* https://github.com/gorhill/ublock/wiki/Static-filter-syntax

As for contacting, it depends on the developer, I personally don't have a problem with it, but some others may have. ISSUES are usually used for reporting problems, issues, making suggestions, feature requests and so on. Some repositories/projects have a DISCUSSIONS tab, where you can ask questions (I think it has to be manually enabled). An other option is contact via email (if the dev has provided one).

**Comment by d0ugparker** [comment]
TY.
