### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Dani-1-2** [KokichaKolevTM/BG-Adblock-list#5]
When I add these to uBlock it appears to block the cookies popup. Think it might be nice to add it here.
www.olx.bg##.ot-sdk-row
www.olx.bg##.ot-fade-in.onetrust-pc-dark-filter

**Comment by KokichaKolevTM** [comment]
Thank you for your suggestion, but this list addresses just ads and privacy, it doesn't deal with cookie popups. If you want to get rid of cookie popups, you could subscribe to the "EasyList – Cookie Notices" list.
